// Export all parser and analyzer functionality
export * from './parser/types.js';
export * from './parser/ast-parser.js';
export { getSWCOptions, createParseError } from './parser/ast-parser.js';
export { SWCASTAnalyzer } from './parser/ast-analyzer.js';
export { VueASTAnalyzer } from './parser/vue-ast-analyzer.js';
export { VueSFCParser, type ParsedVueSFC, type VueSFCSection } from './parser/vue-sfc-parser.js';
export { DefaultDFDBuilder } from './parser/dfd-builder.js';
export * from './parser/index.js';
export * from './analyzers/hooks-analyzer.js';
export * from './analyzers/process-analyzer.js';
export * from './analyzers/conditional-extractor.js';
export * from './analyzers/subgraph-builder.js';
export * from './analyzers/imperative-handle-analyzer.js';
export * from './analyzers/import-detector.js';
export * from './services/type-classifier.js';
export * from './services/type-resolver.js';
export * from './utils/error-handler.js';
export * from './utils/vue-error-handler.js';
export * from './utils/svelte-error-handler.js';
